### ISSUE TITLE
[Fix] Fix tests

### ISSUE THREAD

**Issue by koyablue** [kanta1207/time-tracker-backend#31]
# Overview
Fix some tests that won't pass due to additional implementations.

# Purpose
To ensure safe development.

# Proposal

# Tasks
- [x] Fix src/modules/auth/tests/auth.controller.spec.ts
- [ ] Fix src/modules/workSession/tests/workSession.repository.spec.ts
- [ ] Fix src/modules/tab/tests/tab.controller.spec.ts
- [ ] Fix src/modules/list/tests/list.controller.spec.ts
- [ ] src/modules/task/tests/task.controller.spec.ts
- [ ] src/modules/user/tests/user.controller.spec.ts
